name: Selenium Test with GitHub Actions

on:
  push:
    branches:
      - main # Run the workflow on push to main
  pull_request:
    branches:
      - main # Run the workflow on pull requests targeting main

jobs:
  selenium-test:
    runs-on: ubuntu-latest # Specify that the job should run on the latest Ubuntu runner

    services:
      selenium:
        image: selenium/standalone-chrome # Use the Selenium Standalone Chrome Docker image
        options: --shm-size=2g # Increase the size of shared memory to avoid WebDriver crashes

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 # Checkout the code in the repo

      - name: Set up Python
        uses: actions/setup-python@v2 # Setup Python 3.x on the GitHub runner
        with:
          python-version: "3.9" # Use Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install selenium  # Install Selenium

      - name: Run Selenium tests
        run: |
          python test_selenium.py  # Run the Python test script
